### ISSUE TITLE
fix it

### ISSUE THREAD

**Issue by 7Elohim** [Chainski/IPLogger#1]
please fix it

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/IPLogger/IPLogger.py", line 35, in <module>
    response= requests.get(url.strip(), headers=headers, timeout=5)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

Kesalahan yang Anda alami menunjukkan bahwa Anda tidak memberikan URL yang valid dalam script `IPLogger.py`. Perintah `requests.get()` membutuhkan URL yang valid dengan skema yang tepat seperti `http://` atau `https://`.

Anda perlu memastikan bahwa URL yang Anda berikan di baris 35 script `IPLogger.py` memiliki format yang benar. Jika Anda ingin menggunakan protokol `https://`, pastikan URL dimulai dengan `https://`.

Misalnya, jika Anda ingin mengakses URL "example.com", Anda harus memperbarui baris 35 menjadi sesuatu seperti ini:

```python
response = requests.get("https://example.com", headers=headers, timeout=5)
```

Pastikan Anda mengganti "example.com" dengan URL yang sesuai untuk skenario Anda. Pastikan juga bahwa URL yang Anda berikan tidak kosong seperti yang ditunjukkan oleh pesan kesalahan.

Setelah Anda memperbarui URL dengan benar, jalankan kembali skrip `IPLogger.py` dan seharusnya tidak ada lagi kesalahan "MissingSchema".

**Comment by TrxppyDrkp** [comment]
Did You Put The URL In `Line 34` OF the code?
